id: P008233
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20683
  title: གསོ་རིག་ཟླ་བའི་འོད་སྣང་།
  author: ''
  volumes:
    49a2276c66ed490a8fb92e4fb2e4a6e7:
      image_group_id: I8LS20685
      title: ''
      volume_number: 1
      total_pages: 138
